### ISSUE TITLE
[Fix] Avatar history doesn't update automatically

### ISSUE THREAD

**Issue by Jdbye** [RequiDev/ReModCE#8] opened 2021-09-29 20:04 UTC
Due to VRC oddities in how the UI needs to be visible to be modified/updated, avatar history will never be automatically refreshed as the UI closes before changing avatar. I took the liberty of fixing it myself (seems like it is intended to function this way based on the function being named StartRenderElementsCoroutine)

[VrcUiExtensions.cs](https://github.com/RequiDev/ReModCE/blob/master/ReModCE/VRChat/VrcUiExtensions.cs):
```
using Il2CppSystem.Collections.Generic;
using MelonLoader;
using System.Collections;
using UnityEngine;
using VRC.Core;

namespace ReModCE.VRChat
{
    internal static class VrcUiExtensions
    {
        public static void StartRenderElementsCoroutine(this UiVRCList instance, List<ApiAvatar> avaterList, int offset = 0, bool endOfPickers = true, VRCUiContentButton contentHeaderElement = null)
        {
            MelonCoroutines.Start(RenderElements(0.1f));

            IEnumerator RenderElements(float delay)
            {
                while (!instance.gameObject.activeInHierarchy || !instance.isActiveAndEnabled || instance.isOffScreen ||
                    !instance.enabled)
                    yield return new WaitForSeconds(delay);

                if (instance.scrollRect != null)
                {
                    instance.scrollRect.normalizedPosition = new Vector2(0f, 0f);
                }
                instance.Method_Protected_Void_List_1_T_Int32_Boolean_VRCUiContentButton_0(avaterList, offset, endOfPickers, contentHeaderElement);
            };
        }
    }
}
```

**Comment by RequiDev** [comment] 2021-09-29 20:11
`Method_Protected_Void_List_1_T_Int32_Boolean_VRCUiContentButton_0` is the method that already does the coroutine. I named the method that calls it after the original method.

While your method would indeed work, the problem is now you'll have a coroutine hanging around that will while not a lot, affect your performance when the code doesn't even have to run necessarily.

**Comment by Jdbye** [comment] 2021-09-30 01:33
That is true, but only after an avatar change until the menu is opened again. Avatar changes don't happen frequently enough for it to be a problem IMO. And I don't see another way to solve this problem (but I am still new to MelonLoader and VRC modding so that doesn't mean there isn't one)
I guess for some people it's not a problem, but it was bothering me how the list items are offset too far up (cut off by the Recently Used text) up until I manually hit refresh, on top of the list not refreshing automatically.

**Comment by RequiDev** [comment] 2021-09-30 01:39
The items being offset is indeed somewhat weird. I'll look into fixing that once I find the time.
For now, you'll have to manually press the refresh button to fix that and the fact that the list doesn't refresh automatically all the time.

**Comment by RequiDev** [comment] 2021-11-09 09:10
Due to internal issues with items not showing while reworking everything, your fix has been included in the latest update.
It's still not as consistent as I wish it to be, but seems to be good enough.

**Closed by RequiDev** 2021-11-09 09:10 UTC
